Dig 39 add photo capture upload step
k-henningson/dig-it pull request #26
Opened 2022-12-20 22:51 UTC by k-henningson

![0A59BCA0-224B-4E03-91E3-8D9BA591BC97_1_102_o](https://user-images.githubusercontent.com/100653310/208781626-ed8290e0-ca63-457e-bf6c-9d19e78bb57e.jpeg)

2022-12-26 00:53 UTC, k-henningson commented
![IMG_8122](https://user-images.githubusercontent.com/100653310/209486761-546cbf50-a189-47d3-8047-d34449a030d5.PNG)
Display Title/Date/Type on History Page

2022-12-26 19:53 UTC, k-henningson commented
![IMG_8127](https://user-images.githubusercontent.com/100653310/209579709-496b016a-548b-40f9-a70a-c77767551876.PNG)

2022-12-26 19:56 UTC, j-dowell requested changes

2022-12-26 19:56 UTC, j-dowell commented on modules/screens/test/all-tests/ImageStep.js
> +            aspect: [4, 3],
I don't think we need to let the user edit this, or set the aspect ratio

2022-12-26 19:56 UTC, j-dowell commented on modules/screens/test/all-tests/ImageStep.js
> +            mediaTypes: ImagePicker.MediaTypeOptions.All,
Let's just support images for now, so
```
mediaTypes: MediaTypeOptions.Images
```

2022-12-26 19:56 UTC, j-dowell commented on modules/screens/test/all-tests/ImageStep.js
> +            quality: 1,
We should investigate this more and at least leave a note for later - because we probably want to have some compression enabled here (by setting quality lower than `1`) if we're storing the images in object storage (Filestore)

2022-12-26 19:56 UTC, j-dowell commented on modules/screens/test/all-tests/ImageStep.js
> +        console.log(result);
Please remove logs

2022-12-27 04:35 UTC, j-dowell approved these changes

2022-12-27 04:35 UTC, merged